<?php
header('Content-Type: text/html; charset=utf-8');

/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implements hook_help().
 */
function google_photos_gallery_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    case 'admin/help':
      return '<p>' . t('Use function to load metadata values from google photos urls', array('@blocks' => url('admin/structure/block'))) . '</p>';
  }
}



function google_photos_gallery_get_meta_tags($url){
  // echo "<br><br><br><br><br>url::::".$url;
  // $sites_html =
  $sites_html = mb_convert_encoding(
    file_get_contents($url),
    "HTML-ENTITIES",
    "UTF-8"
  );
  $html = new DOMDocument();
  @$html->loadHTML($sites_html);
  $meta_og_img = null;
  //Get all meta tags and loop through them.
  foreach($html->getElementsByTagName('meta') as $meta) {
      //If the property attribute of the meta tag is og:image
      //echo $meta->getAttribute('property');
      if($meta->getAttribute('property')=='og:title'){
          //Assign the value from content attribute to $meta_og_title
          $meta_og_title = $meta->getAttribute('content');
      }
      if($meta->getAttribute('property')=='og:image'){
          //Assign the value from content attribute to $meta_og_img
          $meta_og_img = $meta->getAttribute('content');
      }
      // if($meta->getAttribute('property')=='og:description'){
      //     //Assign the value from content attribute to $meta_og_description
      //     $meta_og_description = $meta->getAttribute('content');
      // }
  }
  echo "<a href='$url' target='_blank'><img src=$meta_og_img ></a>";
  // echo "<em>$meta_og_description</em>";
  echo "<a href='$url' target='_blank'><h2>$meta_og_title</h2></a>";
}


